#!/bin/bash

echo "🔗 Ejemplos de conexión desde SSH Manager Web App"
echo "================================================"
echo ""
echo "📋 Copia y pega estos datos en tu aplicación web:"
echo ""

echo "🖥️  UBUNTU SERVER"
echo "Host: 172.19.0.7"
echo "Port: 22"
echo "Username: ubuntu"
echo "Password: ubuntu123"
echo "Name: Ubuntu Test Server"
echo ""

echo "🖥️  CENTOS SERVER"
echo "Host: 172.19.0.3"
echo "Port: 22"
echo "Username: centos"
echo "Password: centos123"
echo "Name: CentOS Test Server"
echo ""

echo "🖥️  ALPINE SERVER"
echo "Host: 172.19.0.8"
echo "Port: 22"
echo "Username: alpine"
echo "Password: alpine123"
echo "Name: Alpine Test Server"
echo ""

echo "🖥️  DEBIAN SERVER"
echo "Host: 172.19.0.4"
echo "Port: 22"
echo "Username: debian"
echo "Password: debian123"
echo "Name: Debian Test Server"
echo ""

echo "🖥️  DEVBOX SERVER"
echo "Host: 172.19.0.10"
echo "Port: 22"
echo "Username: developer"
echo "Password: dev123"
echo "Name: DevBox Test Server"
echo ""

echo "🖥️  CUSTOM SERVER"
echo "Host: 172.19.0.11"
echo "Port: 22"
echo "Username: tester"
echo "Password: test123"
echo "Name: Custom Test Server"
echo ""

echo "✅ Todas las conexiones están listas!"
echo "📱 Ve a http://localhost:3000 y crea las conexiones usando estos datos."